countries = {
    "AF": {"id": 1, "name": "Afghanistan", "phonecode": "93", "region": "APAC"},
    "AL": {"id": 2, "name": "Albania", "phonecode": "355", "region": "EU"},
    "DZ": {"id": 3, "name": "Algeria", "phonecode": "213", "region": "MENA"},
    "AS": {"id": 4, "name": "American Samoa", "phonecode": "1684", "region": "APAC"},
    "AD": {"id": 5, "name": "Andorra", "phonecode": "376", "region": "EU"},
    "AO": {"id": 6, "name": "Angola", "phonecode": "244", "region": "MENA"},
    "AI": {"id": 7, "name": "Anguilla", "phonecode": "1264", "region": "LATAM"},
    "AQ": {"id": 8, "name": "Antarctica", "phonecode": "0", "region": "APAC"},
    "AG": {"id": 9, "name": "Antigua And Barbuda", "phonecode": "1268", "region": "LATAM"},
    "AR": {"id": 10, "name": "Argentina", "phonecode": "54", "region": "LATAM"},
    "AM": {"id": 11, "name": "Armenia", "phonecode": "374", "region": "EU"},
    "AW": {"id": 12, "name": "Aruba", "phonecode": "297", "region": "LATAM"},
    "AU": {"id": 13, "name": "Australia", "phonecode": "61", "region": "APAC"},
    "AT": {"id": 14, "name": "Austria", "phonecode": "43", "region": "EU"},
    "AZ": {"id": 15, "name": "Azerbaijan", "phonecode": "994", "region": "EU"},
    "BS": {"id": 16, "name": "Bahamas The", "phonecode": "1242", "region": "LATAM"},
    "BH": {"id": 17, "name": "Bahrain", "phonecode": "973", "region": "MENA"},
    "BD": {"id": 18, "name": "Bangladesh", "phonecode": "880", "region": "APAC"},
    "BB": {"id": 19, "name": "Barbados", "phonecode": "1246", "region": "LATAM"},
    "BY": {"id": 20, "name": "Belarus", "phonecode": "375", "region": "EU"},
    "BE": {"id": 21, "name": "Belgium", "phonecode": "32", "region": "EU"},
    "BZ": {"id": 22, "name": "Belize", "phonecode": "501", "region": "LATAM"},
    "BJ": {"id": 23, "name": "Benin", "phonecode": "229", "region": "MENA"},
    "BM": {"id": 24, "name": "Bermuda", "phonecode": "1441", "region": "LATAM"},
    "BT": {"id": 25, "name": "Bhutan", "phonecode": "975", "region": "APAC"},
    "BO": {"id": 26, "name": "Bolivia", "phonecode": "591", "region": "LATAM"},
    "BA": {"id": 27, "name": "Bosnia and Herzegovina", "phonecode": "387", "region": "EU"},
    "BW": {"id": 28, "name": "Botswana", "phonecode": "267", "region": "MENA"},
    "BV": {"id": 29, "name": "Bouvet Island", "phonecode": "0", "region": "EU"},
    "BR": {"id": 30, "name": "Brazil", "phonecode": "55", "region": "LATAM"},
    "IO": {"id": 31, "name": "British Indian Ocean Territory", "phonecode": "246", "region": "APAC"},
    "BN": {"id": 32, "name": "Brunei", "phonecode": "673", "region": "APAC"},
    "BG": {"id": 33, "name": "Bulgaria", "phonecode": "359", "region": "EU"},
    "BF": {"id": 34, "name": "Burkina Faso", "phonecode": "226", "region": "MENA"},
    "BI": {"id": 35, "name": "Burundi", "phonecode": "257", "region": "MENA"},
    "KH": {"id": 36, "name": "Cambodia", "phonecode": "855", "region": "APAC"},
    "CM": {"id": 37, "name": "Cameroon", "phonecode": "237", "region": "MENA"},
    "CA": {"id": 38, "name": "Canada", "phonecode": "1", "region": "Canada"},
    "CV": {"id": 39, "name": "Cape Verde", "phonecode": "238", "region": "MENA"},
    "KY": {"id": 40, "name": "Cayman Islands", "phonecode": "1345", "region": "LATAM"},
    "CF": {"id": 41, "name": "Central African Republic", "phonecode": "236", "region": "MENA"},
    "TD": {"id": 42, "name": "Chad", "phonecode": "235", "region": "MENA"},
    "CL": {"id": 43, "name": "Chile", "phonecode": "56", "region": "LATAM"},
    "CN": {"id": 44, "name": "China", "phonecode": "86", "region": "APAC"},
    "CX": {"id": 45, "name": "Christmas Island", "phonecode": "61", "region": "APAC"},
    "CC": {"id": 46, "name": "Cocos (Keeling) Islands", "phonecode": "672", "region": "APAC"},
    "CO": {"id": 47, "name": "Colombia", "phonecode": "57", "region": "LATAM"},
    "KM": {"id": 48, "name": "Comoros", "phonecode": "269", "region": "MENA"},
    "CG": {"id": 49, "name": "Republic Of The Congo", "phonecode": "242", "region": "MENA"},
    "CD": {"id": 50, "name": "Democratic Republic Of The Congo", "phonecode": "242", "region": "MENA"},
    "CK": {"id": 51, "name": "Cook Islands", "phonecode": "682", "region": "APAC"},
    "CR": {"id": 52, "name": "Costa Rica", "phonecode": "506", "region": "LATAM"},
    "CI": {"id": 53, "name": "Cote D'Ivoire (Ivory Coast)", "phonecode": "225", "region": "MENA"},
    "HR": {"id": 54, "name": "Croatia (Hrvatska)", "phonecode": "385", "region": "EU"},
    "CU": {"id": 55, "name": "Cuba", "phonecode": "53", "region": "LATAM"},
    "CY": {"id": 56, "name": "Cyprus", "phonecode": "357", "region": "EU"},
    "CZ": {"id": 57, "name": "Czech Republic", "phonecode": "420", "region": "EU"},
    "DK": {"id": 58, "name": "Denmark", "phonecode": "45", "region": "EU"},
    "DJ": {"id": 59, "name": "Djibouti", "phonecode": "253", "region": "MENA"},
    "DM": {"id": 60, "name": "Dominica", "phonecode": "1767", "region": "LATAM"},
    "DO": {"id": 61, "name": "Dominican Republic", "phonecode": "1809", "region": "LATAM"},
    "TP": {"id": 62, "name": "East Timor", "phonecode": "670", "region": "APAC"},
    "EC": {"id": 63, "name": "Ecuador", "phonecode": "593", "region": "LATAM"},
    "EG": {"id": 64, "name": "Egypt", "phonecode": "20", "region": "MENA"},
    "SV": {"id": 65, "name": "El Salvador", "phonecode": "503", "region": "LATAM"},
    "GQ": {"id": 66, "name": "Equatorial Guinea", "phonecode": "240", "region": "MENA"},
    "ER": {"id": 67, "name": "Eritrea", "phonecode": "291", "region": "MENA"},
    "EE": {"id": 68, "name": "Estonia", "phonecode": "372", "region": "EU"},
    "ET": {"id": 69, "name": "Ethiopia", "phonecode": "251", "region": "MENA"},
    "XA": {"id": 70, "name": "External Territories of Australia", "phonecode": "61", "region": "APAC"},
    "FK": {"id": 71, "name": "Falkland Islands", "phonecode": "500", "region": "LATAM"},
    "FO": {"id": 72, "name": "Faroe Islands", "phonecode": "298", "region": "EU"},
    "FJ": {"id": 73, "name": "Fiji Islands", "phonecode": "679", "region": "APAC"},
    "FI": {"id": 74, "name": "Finland", "phonecode": "358", "region": "EU"},
    "FR": {"id": 75, "name": "France", "phonecode": "33", "region": "EU"},
    "GF": {"id": 76, "name": "French Guiana", "phonecode": "594", "region": "LATAM"},
    "PF": {"id": 77, "name": "French Polynesia", "phonecode": "689", "region": "APAC"},
    "TF": {"id": 78, "name": "French Southern Territories", "phonecode": "0", "region": "APAC"},
    "GA": {"id": 79, "name": "Gabon", "phonecode": "241", "region": "MENA"},
    "GM": {"id": 80, "name": "Gambia The", "phonecode": "220", "region": "MENA"},
    "GE": {"id": 81, "name": "Georgia", "phonecode": "995", "region": "EU"},
    "DE": {"id": 82, "name": "Germany", "phonecode": "49", "region": "EU"},
    "GH": {"id": 83, "name": "Ghana", "phonecode": "233", "region": "MENA"},
    "GI": {"id": 84, "name": "Gibraltar", "phonecode": "350", "region": "EU"},
    "GR": {"id": 85, "name": "Greece", "phonecode": "30", "region": "EU"},
    "GL": {"id": 86, "name": "Greenland", "phonecode": "299", "region": "EU"},
    "GD": {"id": 87, "name": "Grenada", "phonecode": "1473", "region": "LATAM"},
    "GP": {"id": 88, "name": "Guadeloupe", "phonecode": "590", "region": "LATAM"},
    "GU": {"id": 89, "name": "Guam", "phonecode": "1671", "region": "APAC"},
    "GT": {"id": 90, "name": "Guatemala", "phonecode": "502", "region": "LATAM"},
    "XU": {"id": 91, "name": "Guernsey and Alderney", "phonecode": "44", "region": "UK"},
    "GN": {"id": 92, "name": "Guinea", "phonecode": "224", "region": "MENA"},
    "GW": {"id": 93, "name": "Guinea-Bissau", "phonecode": "245", "region": "MENA"},
    "GY": {"id": 94, "name": "Guyana", "phonecode": "592", "region": "LATAM"},
    "HT": {"id": 95, "name": "Haiti", "phonecode": "509", "region": "LATAM"},
    "HM": {"id": 96, "name": "Heard and McDonald Islands", "phonecode": "0", "region": "APAC"},
    "HN": {"id": 97, "name": "Honduras", "phonecode": "504", "region": "LATAM"},
    "HK": {"id": 98, "name": "Hong Kong S.A.R.", "phonecode": "852", "region": "APAC"},
    "HU": {"id": 99, "name": "Hungary", "phonecode": "36", "region": "EU"},
    "IS": {"id": 100, "name": "Iceland", "phonecode": "354", "region": "EU"},
    "BO": {"id": 27, "name": "Bolivia", "phonecode": "591", "region": "LATAM"},
    "BA": {"id": 28, "name": "Bosnia and Herzegovina", "phonecode": "387", "region": "EU"},
    "BW": {"id": 29, "name": "Botswana", "phonecode": "267", "region": "MENA"},
    "BV": {"id": 30, "name": "Bouvet Island", "phonecode": "0", "region": "EU"},
    "BR": {"id": 31, "name": "Brazil", "phonecode": "55", "region": "LATAM"},
    "IO": {"id": 32, "name": "British Indian Ocean Territory", "phonecode": "246", "region": "APAC"},
    "BN": {"id": 33, "name": "Brunei Darussalam", "phonecode": "673", "region": "APAC"},
    "BG": {"id": 34, "name": "Bulgaria", "phonecode": "359", "region": "EU"},
    "BF": {"id": 35, "name": "Burkina Faso", "phonecode": "226", "region": "MENA"},
    "BI": {"id": 36, "name": "Burundi", "phonecode": "257", "region": "MENA"},
    "KH": {"id": 37, "name": "Cambodia", "phonecode": "855", "region": "APAC"},
    "CM": {"id": 38, "name": "Cameroon", "phonecode": "237", "region": "MENA"},
    "CA": {"id": 39, "name": "Canada", "phonecode": "1", "region": "Canada"},
    "CV": {"id": 40, "name": "Cape Verde", "phonecode": "238", "region": "MENA"},
    "KY": {"id": 41, "name": "Cayman Islands", "phonecode": "1345", "region": "LATAM"},
    "CF": {"id": 42, "name": "Central African Republic", "phonecode": "236", "region": "MENA"},
    "TD": {"id": 43, "name": "Chad", "phonecode": "235", "region": "MENA"},
    "CL": {"id": 44, "name": "Chile", "phonecode": "56", "region": "LATAM"},
    "CN": {"id": 45, "name": "China", "phonecode": "86", "region": "APAC"},
    "CX": {"id": 46, "name": "Christmas Island", "phonecode": "61", "region": "APAC"},
    "CC": {"id": 47, "name": "Cocos (Keeling) Islands", "phonecode": "672", "region": "APAC"},
    "CO": {"id": 48, "name": "Colombia", "phonecode": "57", "region": "LATAM"},
    "KM": {"id": 49, "name": "Comoros", "phonecode": "269", "region": "MENA"},
    "CG": {"id": 50, "name": "Congo", "phonecode": "242", "region": "MENA"},
    "CD": {"id": 51, "name": "Congo, Democratic Republic of the", "phonecode": "242", "region": "MENA"},
    "CK": {"id": 52, "name": "Cook Islands", "phonecode": "682", "region": "APAC"},
    "CR": {"id": 53, "name": "Costa Rica", "phonecode": "506", "region": "LATAM"},
    "CI": {"id": 54, "name": "Cote D'Ivoire", "phonecode": "225", "region": "MENA"},
    "HR": {"id": 55, "name": "Croatia", "phonecode": "385", "region": "EU"},
    "CU": {"id": 56, "name": "Cuba", "phonecode": "53", "region": "LATAM"},
    "CY": {"id": 57, "name": "Cyprus", "phonecode": "357", "region": "EU"},
    "CZ": {"id": 58, "name": "Czech Republic", "phonecode": "420", "region": "EU"},
    "DK": {"id": 59, "name": "Denmark", "phonecode": "45", "region": "EU"},
    "DJ": {"id": 60, "name": "Djibouti", "phonecode": "253", "region": "MENA"},
    "DM": {"id": 61, "name": "Dominica", "phonecode": "1767", "region": "LATAM"},
    "DO": {"id": 62, "name": "Dominican Republic", "phonecode": "1809", "region": "LATAM"},
    "EC": {"id": 63, "name": "Ecuador", "phonecode": "593", "region": "LATAM"},
    "EG": {"id": 64, "name": "Egypt", "phonecode": "20", "region": "MENA"},
    "SV": {"id": 65, "name": "El Salvador", "phonecode": "503", "region": "LATAM"},
    "GQ": {"id": 66, "name": "Equatorial Guinea", "phonecode": "240", "region": "MENA"},
    "ER": {"id": 67, "name": "Eritrea", "phonecode": "291", "region": "MENA"},
    "EE": {"id": 68, "name": "Estonia", "phonecode": "372", "region": "EU"},
    "ET": {"id": 69, "name": "Ethiopia", "phonecode": "251", "region": "MENA"},
    "FK": {"id": 70, "name": "Falkland Islands (Malvinas)", "phonecode": "500", "region": "LATAM"},
    "FO": {"id": 71, "name": "Faroe Islands", "phonecode": "298", "region": "EU"},
    "FJ": {"id": 72, "name": "Fiji", "phonecode": "679", "region": "APAC"},
    "FI": {"id": 73, "name": "Finland", "phonecode": "358", "region": "EU"},
    "FR": {"id": 74, "name": "France", "phonecode": "33", "region": "EU"},
    "GF": {"id": 75, "name": "French Guiana", "phonecode": "594", "region": "LATAM"},
    "PF": {"id": 76, "name": "French Polynesia", "phonecode": "689", "region": "APAC"},
    "TF": {"id": 77, "name": "French Southern Territories", "phonecode": "0", "region": "APAC"},
    "GA": {"id": 78, "name": "Gabon", "phonecode": "241", "region": "MENA"},
    "GM": {"id": 79, "name": "Gambia", "phonecode": "220", "region": "MENA"},
    "GE": {"id": 80, "name": "Georgia", "phonecode": "995", "region": "EU"},
    "DE": {"id": 81, "name": "Germany", "phonecode": "49", "region": "EU"},
    "GH": {"id": 82, "name": "Ghana", "phonecode": "233", "region": "MENA"},
    "GI": {"id": 83, "name": "Gibraltar", "phonecode": "350", "region": "EU"},
    "GR": {"id": 84, "name": "Greece", "phonecode": "30", "region": "EU"},
    "GL": {"id": 85, "name": "Greenland", "phonecode": "299", "region": "EU"},
    "GD": {"id": 86, "name": "Grenada", "phonecode": "1473", "region": "LATAM"},
    "GP": {"id": 87, "name": "Guadeloupe", "phonecode": "590", "region": "LATAM"},
    "GU": {"id": 88, "name": "Guam", "phonecode": "1671", "region": "APAC"},
    "GT": {"id": 89, "name": "Guatemala", "phonecode": "502", "region": "LATAM"},
    "GN": {"id": 90, "name": "Guinea", "phonecode": "224", "region": "MENA"},
    "GW": {"id": 91, "name": "Guinea-Bissau", "phonecode": "245", "region": "MENA"},
    "GY": {"id": 92, "name": "Guyana", "phonecode": "592", "region": "LATAM"},
    "HT": {"id": 93, "name": "Haiti", "phonecode": "509", "region": "LATAM"},
    "HM": {"id": 94, "name": "Heard Island and Mcdonald Islands", "phonecode": "0", "region": "APAC"},
    "VA": {"id": 95, "name": "Holy See (Vatican City State)", "phonecode": "39", "region": "EU"},
    "HN": {"id": 96, "name": "Honduras", "phonecode": "504", "region": "LATAM"},
    "HK": {"id": 97, "name": "Hong Kong", "phonecode": "852", "region": "APAC"},
    "HU": {"id": 98, "name": "Hungary", "phonecode": "36", "region": "EU"},
    "IS": {"id": 99, "name": "Iceland", "phonecode": "354", "region": "EU"},
    "IN": {"id": 100, "name": "India", "phonecode": "91", "region": "APAC"},
     "ID": {"id": 101, "name": "Indonesia", "phonecode": "62", "region": "APAC"},
    "IR": {"id": 102, "name": "Iran, Islamic Republic of", "phonecode": "98", "region": "MENA"},
    "IQ": {"id": 103, "name": "Iraq", "phonecode": "964", "region": "MENA"},
    "IE": {"id": 104, "name": "Ireland", "phonecode": "353", "region": "EU"},
    "IL": {"id": 105, "name": "Israel", "phonecode": "972", "region": "MENA"},
    "IT": {"id": 106, "name": "Italy", "phonecode": "39", "region": "EU"},
    "JM": {"id": 107, "name": "Jamaica", "phonecode": "1876", "region": "LATAM"},
    "JP": {"id": 108, "name": "Japan", "phonecode": "81", "region": "APAC"},
    "JO": {"id": 109, "name": "Jordan", "phonecode": "962", "region": "MENA"},
    "KZ": {"id": 110, "name": "Kazakhstan", "phonecode": "7", "region": "APAC"},
    "KE": {"id": 111, "name": "Kenya", "phonecode": "254", "region": "MENA"},
    "KI": {"id": 112, "name": "Kiribati", "phonecode": "686", "region": "APAC"},
    "KP": {"id": 113, "name": "Korea, Democratic People's Republic of", "phonecode": "850", "region": "APAC"},
    "KR": {"id": 114, "name": "Korea, Republic of", "phonecode": "82", "region": "APAC"},
    "KW": {"id": 115, "name": "Kuwait", "phonecode": "965", "region": "MENA"},
    "KG": {"id": 116, "name": "Kyrgyzstan", "phonecode": "996", "region": "APAC"},
    "LA": {"id": 117, "name": "Lao People's Democratic Republic", "phonecode": "856", "region": "APAC"},
    "LV": {"id": 118, "name": "Latvia", "phonecode": "371", "region": "EU"},
    "LB": {"id": 119, "name": "Lebanon", "phonecode": "961", "region": "MENA"},
    "LS": {"id": 120, "name": "Lesotho", "phonecode": "266", "region": "MENA"},
    "LR": {"id": 121, "name": "Liberia", "phonecode": "231", "region": "MENA"},
    "LY": {"id": 122, "name": "Libyan Arab Jamahiriya", "phonecode": "218", "region": "MENA"},
    "LI": {"id": 123, "name": "Liechtenstein", "phonecode": "423", "region": "EU"},
    "LT": {"id": 124, "name": "Lithuania", "phonecode": "370", "region": "EU"},
    "LU": {"id": 125, "name": "Luxembourg", "phonecode": "352", "region": "EU"},
    "MO": {"id": 126, "name": "Macao", "phonecode": "853", "region": "APAC"},
    "MK": {"id": 127, "name": "Macedonia, the Former Yugoslav Republic of", "phonecode": "389", "region": "EU"},
    "MG": {"id": 128, "name": "Madagascar", "phonecode": "261", "region": "MENA"},
    "MW": {"id": 129, "name": "Malawi", "phonecode": "265", "region": "MENA"},
    "MY": {"id": 130, "name": "Malaysia", "phonecode": "60", "region": "APAC"},
    "MV": {"id": 131, "name": "Maldives", "phonecode": "960", "region": "APAC"},
    "ML": {"id": 132, "name": "Mali", "phonecode": "223", "region": "MENA"},
    "MT": {"id": 133, "name": "Malta", "phonecode": "356", "region": "EU"},
    "MH": {"id": 134, "name": "Marshall Islands", "phonecode": "692", "region": "APAC"},
    "MQ": {"id": 135, "name": "Martinique", "phonecode": "596", "region": "LATAM"},
    "MR": {"id": 136, "name": "Mauritania", "phonecode": "222", "region": "MENA"},
    "MU": {"id": 137, "name": "Mauritius", "phonecode": "230", "region": "MENA"},
    "YT": {"id": 138, "name": "Mayotte", "phonecode": "269", "region": "MENA"},
    "MX": {"id": 139, "name": "Mexico", "phonecode": "52", "region": "LATAM"},
    "FM": {"id": 140, "name": "Micronesia, Federated States of", "phonecode": "691", "region": "APAC"},
    "MD": {"id": 141, "name": "Moldova, Republic of", "phonecode": "373", "region": "EU"},
    "MC": {"id": 142, "name": "Monaco", "phonecode": "377", "region": "EU"},
    "MN": {"id": 143, "name": "Mongolia", "phonecode": "976", "region": "APAC"},
    "MS": {"id": 144, "name": "Montserrat", "phonecode": "1664", "region": "LATAM"},
    "MA": {"id": 145, "name": "Morocco", "phonecode": "212", "region": "MENA"},
    "MZ": {"id": 146, "name": "Mozambique", "phonecode": "258", "region": "MENA"},
    "MM": {"id": 147, "name": "Myanmar", "phonecode": "95", "region": "APAC"},
    "NA": {"id": 148, "name": "Namibia", "phonecode": "264", "region": "MENA"},
    "NR": {"id": 149, "name": "Nauru", "phonecode": "674", "region": "APAC"},
    "NP": {"id": 150, "name": "Nepal", "phonecode": "977", "region": "APAC"},
     "NL": {"id": 151, "name": "Netherlands", "phonecode": "31", "region": "EU"},
    "AN": {"id": 152, "name": "Netherlands Antilles", "phonecode": "599", "region": "LATAM"},
    "NC": {"id": 153, "name": "New Caledonia", "phonecode": "687", "region": "APAC"},
    "NZ": {"id": 154, "name": "New Zealand", "phonecode": "64", "region": "APAC"},
    "NI": {"id": 155, "name": "Nicaragua", "phonecode": "505", "region": "LATAM"},
    "NE": {"id": 156, "name": "Niger", "phonecode": "227", "region": "MENA"},
    "NG": {"id": 157, "name": "Nigeria", "phonecode": "234", "region": "MENA"},
    "NU": {"id": 158, "name": "Niue", "phonecode": "683", "region": "APAC"},
    "NF": {"id": 159, "name": "Norfolk Island", "phonecode": "672", "region": "APAC"},
    "MP": {"id": 160, "name": "Northern Mariana Islands", "phonecode": "1670", "region": "APAC"},
    "NO": {"id": 161, "name": "Norway", "phonecode": "47", "region": "EU"},
    "OM": {"id": 162, "name": "Oman", "phonecode": "968", "region": "MENA"},
    "PK": {"id": 163, "name": "Pakistan", "phonecode": "92", "region": "APAC"},
    "PW": {"id": 164, "name": "Palau", "phonecode": "680", "region": "APAC"},
    "PS": {"id": 165, "name": "Palestinian Territory, Occupied", "phonecode": "970", "region": "MENA"},
    "PA": {"id": 166, "name": "Panama", "phonecode": "507", "region": "LATAM"},
    "PG": {"id": 167, "name": "Papua New Guinea", "phonecode": "675", "region": "APAC"},
    "PY": {"id": 168, "name": "Paraguay", "phonecode": "595", "region": "LATAM"},
    "PE": {"id": 169, "name": "Peru", "phonecode": "51", "region": "LATAM"},
    "PH": {"id": 170, "name": "Philippines", "phonecode": "63", "region": "APAC"},
    "PN": {"id": 171, "name": "Pitcairn", "phonecode": "0", "region": "APAC"},
    "PL": {"id": 172, "name": "Poland", "phonecode": "48", "region": "EU"},
    "PT": {"id": 173, "name": "Portugal", "phonecode": "351", "region": "EU"},
    "PR": {"id": 174, "name": "Puerto Rico", "phonecode": "1787", "region": "LATAM"},
    "QA": {"id": 175, "name": "Qatar", "phonecode": "974", "region": "MENA"},
    "RE": {"id": 176, "name": "Reunion", "phonecode": "262", "region": "MENA"},
    "RO": {"id": 177, "name": "Romania", "phonecode": "40", "region": "EU"},
    "RU": {"id": 178, "name": "Russian Federation", "phonecode": "7", "region": "EU"},
    "RW": {"id": 179, "name": "Rwanda", "phonecode": "250", "region": "MENA"},
    "SH": {"id": 180, "name": "Saint Helena", "phonecode": "290", "region": "MENA"},
    "KN": {"id": 181, "name": "Saint Kitts and Nevis", "phonecode": "1869", "region": "LATAM"},
    "LC": {"id": 182, "name": "Saint Lucia", "phonecode": "1758", "region": "LATAM"},
    "PM": {"id": 183, "name": "Saint Pierre and Miquelon", "phonecode": "508", "region": "LATAM"},
    "VC": {"id": 184, "name": "Saint Vincent and the Grenadines", "phonecode": "1784", "region": "LATAM"},
    "WS": {"id": 185, "name": "Samoa", "phonecode": "684", "region": "APAC"},
    "SM": {"id": 186, "name": "San Marino", "phonecode": "378", "region": "EU"},
    "ST": {"id": 187, "name": "Sao Tome and Principe", "phonecode": "239", "region": "MENA"},
    "SA": {"id": 188, "name": "Saudi Arabia", "phonecode": "966", "region": "MENA"},
    "SN": {"id": 189, "name": "Senegal", "phonecode": "221", "region": "MENA"},
    "RS": {"id": 190, "name": "Serbia", "phonecode": "381", "region": "EU"},
    "SC": {"id": 191, "name": "Seychelles", "phonecode": "248", "region": "MENA"},
    "SL": {"id": 192, "name": "Sierra Leone", "phonecode": "232", "region": "MENA"},
    "SG": {"id": 193, "name": "Singapore", "phonecode": "65", "region": "APAC"},
    "SK": {"id": 194, "name": "Slovakia", "phonecode": "421", "region": "EU"},
    "SI": {"id": 195, "name": "Slovenia", "phonecode": "386", "region": "EU"},
    "SB": {"id": 196, "name": "Solomon Islands", "phonecode": "677", "region": "APAC"},
    "SO": {"id": 197, "name": "Somalia", "phonecode": "252", "region": "MENA"},
    "ZA": {"id": 198, "name": "South Africa", "phonecode": "27", "region": "MENA"},
    "GS": {"id": 199, "name": "South Georgia and the South Sandwich Islands", "phonecode": "0", "region": "MENA"},
    "SS": {"id": 200, "name": "South Sudan", "phonecode": "211", "region": "MENA"},
    "TT": {"id": 200, "name": "Trinidad and Tobago", "phonecode": "1868", "region": "LATAM"},
  "TN": {"id": 201, "name": "Tunisia", "phonecode": "216", "region": "MENA"},
  "TR": {"id": 202, "name": "Turkey", "phonecode": "90", "region": "MENA"},
  "TM": {"id": 203, "name": "Turkmenistan", "phonecode": "7370", "region": "APAC"},
  "TC": {"id": 204, "name": "Turks and Caicos Islands", "phonecode": "1649", "region": "LATAM"},
  "TV": {"id": 205, "name": "Tuvalu", "phonecode": "688", "region": "APAC"},
  "UG": {"id": 206, "name": "Uganda", "phonecode": "256", "region": "MENA"},
  "UA": {"id": 207, "name": "Ukraine", "phonecode": "380", "region": "EU"},
  "AE": {"id": 208, "name": "United Arab Emirates", "phonecode": "971", "region": "MENA"},
  "DUB": {"id": 500, "name": "Dubai", "phonecode": "7971", "region": "MENA"},

  "GB": {"id": 209, "name": "United Kingdom", "phonecode": "44", "region": "UK"},
  "US": {"id": 210, "name": "United States", "phonecode": "1", "region": "USA"},
  "UM": {"id": 211, "name": "United States Minor Outlying Islands", "phonecode": "1", "region": "USA"},
  "UY": {"id": 212, "name": "Uruguay", "phonecode": "598", "region": "LATAM"},
  "UZ": {"id": 213, "name": "Uzbekistan", "phonecode": "998", "region": "APAC"},
  "VU": {"id": 214, "name": "Vanuatu", "phonecode": "678", "region": "APAC"},
  "VE": {"id": 215, "name": "Venezuela", "phonecode": "58", "region": "LATAM"},
  "VN": {"id": 216, "name": "Viet Nam", "phonecode": "84", "region": "APAC"},
  "VG": {"id": 217, "name": "Virgin Islands, British", "phonecode": "1284", "region": "LATAM"},
  "VI": {"id": 218, "name": "Virgin Islands, U.S.", "phonecode": "1340", "region": "LATAM"},
  "WF": {"id": 219, "name": "Wallis and Futuna", "phonecode": "681", "region": "APAC"},
  "EH": {"id": 220, "name": "Western Sahara", "phonecode": "212", "region": "MENA"},
  "YE": {"id": 221, "name": "Yemen", "phonecode": "967", "region": "MENA"},
  "ZM": {"id": 222, "name": "Zambia", "phonecode": "260", "region": "MENA"},
  "ZW": {"id": 223, "name": "Zimbabwe", "phonecode": "263", "region": "MENA"}
}
